### ISSUE TITLE
BUG REPORT: Recent changes won't compile

### ISSUE THREAD

**Issue by wise200** [keziakl/konglish-analysis#1]
Hi. I pulled the latest commit and attempted to compile, but there were no files to compile. There was only a README. Perhaps some files were accidentally removed in the most recent commit? This is very disappointing, as I was so happy when I found this repo, I even gave it a star! Unfortunately, it seems the devs are not committed  to maintaining a functioning code base. 

grrrrrrrrrrrrrr 😠

**Comment by keziakl** [comment]
Hey! Haha the devs can be a bit slow sometimes.
I actually just started this project yesterday, so I haven't uploaded the code yet. As of now I have an API twitter scraper that's collected my corpus (no graphs or analyses yet)! I'll update you when I've gotten the computational analyses done (hopefully by tonight) so you can have a peek before I integrate it into my website, Google NGrams viewer style. The corpus will either be uploaded directly here or stored using AWS depending on how large it gets. It'll be public so you can use it to your liking. Happy coding :) @wise200

**Comment by wise200** [comment]
[Liked a message](https://youtu.be/vsocuSfR22k)
